<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SEO Performance Report - {{ $organization->name }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #1e293b;
            line-height: 1.5;
            margin: 0;
            padding: 0;
        }
        @page {
            margin: 1.5cm;
        }
        .page-break {
            page-break-after: always;
        }
        .cover-page {
            text-align: center;
            padding-top: 5cm;
        }
        .logo {
            font-size: 32px;
            font-weight: 900;
            color: #2563eb;
            letter-spacing: -1px;
            margin-bottom: 2cm;
        }
        h1 {
            font-size: 36px;
            font-weight: 800;
            margin-bottom: 0.5cm;
            color: #0f172a;
        }
        .subtitle {
            font-size: 18px;
            color: #64748b;
            margin-bottom: 3cm;
        }
        .meta {
            font-size: 14px;
            color: #94a3b8;
        }
        .section-header {
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 10px;
            margin-bottom: 20px;
            margin-top: 40px;
        }
        .section-title {
            font-size: 20px;
            font-weight: 800;
            color: #0f172a;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .property-header {
            background-color: #f8fafc;
            padding: 20px;
            border-radius: 12px;
            margin-bottom: 30px;
        }
        .property-name {
            font-size: 24px;
            font-weight: 800;
            color: #1e293b;
            margin: 0;
        }
        .property-url {
            font-size: 14px;
            color: #64748b;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            text-align: left;
            font-size: 11px;
            font-weight: 800;
            text-transform: uppercase;
            color: #64748b;
            padding: 10px;
            border-bottom: 1px solid #e2e8f0;
        }
        td {
            padding: 12px 10px;
            font-size: 13px;
            border-bottom: 1px solid #f1f5f9;
        }
        .metric-card {
            display: inline-block;
            width: 23%;
            background: #fff;
            border: 1px solid #e2e8f0;
            padding: 15px;
            border-radius: 10px;
            margin-right: 1.5%;
            margin-bottom: 15px;
            vertical-align: top;
        }
        .metric-value {
            font-size: 18px;
            font-weight: 800;
            color: #0f172a;
        }
        .metric-label {
            font-size: 10px;
            font-weight: 700;
            color: #64748b;
            text-transform: uppercase;
            margin-top: 2px;
        }
        .metric-change {
            font-size: 10px;
            font-weight: 700;
            margin-top: 5px;
        }
        .trend-up { color: #10b981; }
        .trend-down { color: #ef4444; }
        .alert-card {
            padding: 12px;
            border-radius: 8px;
            margin-bottom: 10px;
            font-size: 12px;
        }
        .alert-critical { background-color: #fef2f2; border-left: 4px solid #ef4444; }
        .alert-high { background-color: #fffbef; border-left: 4px solid #f59e0b; }
        .alert-info { background-color: #f0f9ff; border-left: 4px solid #0ea5e9; }
        .insight-box {
            background-color: #f1f5f9;
            padding: 20px;
            border-radius: 12px;
            font-size: 14px;
            color: #334155;
            font-style: italic;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            font-size: 10px;
            color: #94a3b8;
            text-align: center;
            padding: 20px 0;
        }
    </style>
</head>
<body>
    <div class="footer">
        © {{ date('Y') }} {{ $organization->name }}. Generated by Pique AI Intelligence. Page <span class="pagenum"></span>
    </div>

    <!-- Cover Page -->
    <div class="cover-page page-break">
        <div class="logo">Pique AI</div>
        <h1>SEO PERFORMANCE REPORT</h1>
        <div class="subtitle">{{ $organization->name }}</div>
        
        <div class="meta">
            <strong>Properties Covered:</strong><br>
            @foreach($reports as $r)
                {{ $r['property']['name'] }}{{ !$loop->last ? ', ' : '' }}
            @endforeach
            <br><br>
            <strong>Date Range:</strong><br>
            {{ $reports[0]['start_date'] }} to {{ $reports[0]['end_date'] }}
            <br><br>
            <strong>Generated On:</strong><br>
            {{ $generated_at }}
        </div>
    </div>

    @foreach($reports as $report)
        <div class="property-header">
            <h2 class="property-name">{{ $report['property']['name'] }}</h2>
            <div class="property-url">{{ $report['property']['website_url'] }}</div>
        </div>

        @if(isset($report['sections']['overview']))
            <div class="section-header">
                <div class="section-title">Executive Overview</div>
            </div>
            <div style="margin-bottom: 20px;">
                @foreach($report['sections']['overview']['metrics'] ?? [] as $key => $metric)
                    @if(in_array($key, ['sessions', 'users', 'pageviews', 'conversions']))
                    <div class="metric-card">
                        <div class="metric-value">{{ number_format($metric['current']) }}</div>
                        <div class="metric-label">{{ str_replace('_', ' ', $key) }}</div>
                        <div class="metric-change {{ ($metric['change'] ?? 0) >= 0 ? 'trend-up' : 'trend-down' }}">
                            {{ ($metric['change'] ?? 0) >= 0 ? '+' : '' }}{{ number_format($metric['change'] ?? 0, 1) }}% vs prev
                        </div>
                    </div>
                    @endif
                @endforeach
            </div>
        @endif

        @if(isset($report['sections']['traffic']))
            <div class="section-header">
                <div class="section-title">Traffic Trends</div>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Sessions</th>
                        <th>Users</th>
                        <th>Conversions</th>
                    </tr>
                </thead>
                <tbody>
                    @php 
                        $trends = array_slice($report['sections']['traffic'] ?? [], -7);
                    @endphp
                    @foreach($trends as $day)
                        <tr>
                            <td>{{ $day['date'] }}</td>
                            <td>{{ number_format($day['sessions'] ?? 0) }}</td>
                            <td>{{ number_format($day['users'] ?? 0) }}</td>
                            <td>{{ number_format($day['conversions'] ?? 0) }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif

        @if(isset($report['sections']['acquisition']))
            <div class="section-header">
                <div class="section-title">Acquisition Channels</div>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Source / Medium</th>
                        <th>Sessions</th>
                        <th>Users</th>
                        <th>Ads Clicks</th>
                    </tr>
                </thead>
                <tbody>
                    @php 
                        $acq = array_slice($report['sections']['acquisition'] ?? [], 0, 8);
                    @endphp
                    @foreach($acq as $row)
                        <tr>
                            <td>{{ $row['source_medium'] ?? 'Direct' }}</td>
                            <td>{{ number_format($row['sessions'] ?? 0) }}</td>
                            <td>{{ number_format($row['users'] ?? 0) }}</td>
                            <td>{{ number_format($row['ad_clicks'] ?? 0) }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endif

        @if(isset($report['sections']['seo_intelligence']))
            <div class="section-header">
                <div class="section-title">SEO Intelligence & Alerts</div>
            </div>
            @if(count($report['sections']['seo_intelligence']['alerts'] ?? []) > 0)
                @foreach($report['sections']['seo_intelligence']['alerts'] as $alert)
                    <div class="alert-card alert-{{ $alert['severity'] ?? 'info' }}">
                        <strong>[{{ strtoupper($alert['severity'] ?? 'info') }}]</strong> {{ $alert['title'] ?? 'Signal' }}: 
                        {{ $alert['message'] ?? '' }}
                    </div>
                @endforeach
            @else
                <p style="font-size: 13px; color: #64748b;">No critical SEO issues detected during this period.</p>
            @endif
        @endif

        @if(isset($report['sections']['insights']) && $report['sections']['insights'])
            <div class="section-header">
                <div class="section-title">Pique AI Insights</div>
            </div>
            <div class="insight-box">
                {!! nl2br(e($report['sections']['insights']->content ?? 'No insight data available.')) !!}
            </div>
        @endif

        @if(isset($report['sections']['forecasts']))
            <div class="section-header">
                <div class="section-title">Predictive Forecasts</div>
            </div>
            <p style="font-size: 13px; color: #475569; margin-bottom: 10px;">
                Based on historical trends, Pique predicts the following performance for the next 14 days:
            </p>
            <div style="margin-bottom: 20px;">
                @php $sess = $report['sections']['forecasts']['sessions']; @endphp
                @if($sess)
                    <div class="metric-card" style="width: 48%;">
                        <div class="metric-value">{{ number_format($sess['projected_total'] ?? 0) }}</div>
                        <div class="metric-label">Projected Sessions</div>
                        <div class="metric-change {{ ($sess['confidence'] ?? 0) > 0.7 ? 'trend-up' : '' }}">
                            Confidence: {{ round(($sess['confidence'] ?? 0) * 100) }}%
                        </div>
                    </div>
                @endif
                
                @php $conv = $report['sections']['forecasts']['conversions']; @endphp
                @if($conv)
                    <div class="metric-card" style="width: 48%;">
                        <div class="metric-value">{{ number_format($conv['projected_total'] ?? 0) }}</div>
                        <div class="metric-label">Projected Conversions</div>
                        <div class="metric-change">
                            Trend: {{ $conv['trend'] ?? 'stable' }}
                        </div>
                    </div>
                @endif
            </div>
            
            @if(isset($report['sections']['forecasts']['strategy']['recommendation']))
                <div style="background-color: #fdf2f8; border: 1px solid #fbcfe8; padding: 15px; border-radius: 10px; font-size: 12px; color: #831843;">
                    <strong>Strategic Recommendation:</strong><br>
                    {{ $report['sections']['forecasts']['strategy']['recommendation'] }}
                </div>
            @endif
        @endif

        @if(!$loop->last)
            <div class="page-break"></div>
        @endif
    @endforeach

</body>
</html>
